version: 0.2
env: 
  parameter-store: 
    MONGO_URL: "/ankur/mongo"
phases:  
    
  pre_build:
    commands:
      - echo Build Started on `date`
      - echo MONGODB_URI=$MONGO_URL > .env
      - echo PORT=3000 > .env
       
  build:
    commands:
      - npm install
      - npm install pm2 -g 
  post_build:
    commands:
       - echo Build Completed on `date`

artifacts:
  files:
    - '**/*'
